# Site settings
title: One Trip To Another
subtitle: "Journal of Chinmay Nema"
email: chinmay.nema1993@gmail.com.
description: "Make the footer happy by entering a short description about yourself here"
baseurl: ""
url: "https://onetriptoanother.com"
#twitter_username: "rowanoulton"
#github_username:  "rowanoulton"
#instagram_username: "rowanoulton"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed
