# Site setings
name: 'One Trip To Another'
description: 'Chinmay Nema'
#meta_description: ''
#logo: 'assets/images/logo.png'
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'authorimage.jpg'
  greetings: "One Trip To Another"
favicon: 'assets/images/favicon.ico'
baseurl:
production_url: https://onetriptoanother.com/
url: "https://www.onetriptoanother.com"
# disqus: 'justgoodthemes'
mailchimp_url: 'https://onetriptoanother.us10.list-manage.com/subscribe/post?u=be6be26bf7dc215ff3f889c9a&amp;id=c0bad4bb03'
# Add your GA Tracking Id
ga_analytics: 'UA-170227368-1'

# Contact form setings
email: chinmay.nema1993@gmail.com
contact_page_description: "I am always up to discuss anything about travel - your or mine. Feel free to reach out and I would love to hear from you!<br><br>

E-mail: chinmay.nema1993@gmail.com<br>
Facebook: www.facebook.com/chinmay.nema<br>
Instagram: www.instagram.com/chinmaynema/<br>
LinkedIn: www.linkedin.com/in/chinmay-nema/"
#thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
# twitter: 'justgoodthemes'
facebook: 'chinmay.nema'
# github: ''
# codepen: 'username'
# dribbble: 'username'
# medium: '@username'
instagram: 'chinmaynema'
# pinterest: 'username'
linkedin: 'chinmay-nema'
# producthunt: '@username'
# quora: 'username'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
#  - text: Projects
#    url: /projects
#  - text: Experience
#    url: /experience
  - text: Contact
    url: /contact

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
